import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Layout from "@/components/base-comp/Layout";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Movie app",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
});

// Update the body className to use Montserrat
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Layout>
          <AuthProvider>{children}</AuthProvider>
        </Layout>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
